### ISSUE TITLE
Active plots show - 1/4 phase and - 1%

### ISSUE THREAD

**Issue by maded2** [maded2/plotng#58]
@squizzling

Seeing reports from users, saying the active plot table now show '-1/4' phase and -1% progress.  Can you double check.

Thanks

**Comment by squizzling** [comment]
I'll take a look, -1 means there was no "/" in phase, and Progress was "" though.

**Comment by squizzling** [comment]
I can't see any obvious reason for it, my best guess is the addition of `PlotSize` has confused the Gob encoding if the client and server has a mismatch of datatypes,  I don't know if that's **actually** a thing or not though, I was unable to reproduce it with either size being downrev.

Can you ask them to check the server output? It writes the raw string with its summary, both for phase and progress, for each active plot.  If they're invalid then it's something on the server failing to parse it, if they're valid then it's probably the encoding, because we're reading an empty string.

**Comment by maded2** [comment]
thanks for looking into this.  I may well be version mismatch between server and ui.  I will do more investigation on my side.

**Comment by yarruslan** [comment]
I see similar behaviour on my Ubuntu machine, with plotng version I got on 22nd of May.
Additional symptom: plotng server does not send logs to console after 5 initial lines. Last line i see is this:
`Starting plotting progress into temporary dirs: /mnt/nvme/chiatemp1 and /mnt/ntfs1/chia_plots`

I see in debug that problem happens here: 
```
func (ap *ActivePlot) processLogs(in io.ReadCloser)
...
>		if s, err := reader.ReadString('\n'); err != nil {
```
If I do "Step over" on this line after ap.Tail already have 5 strings, it never return control back, something hangs.
Chia process keeps writing to disk. Not sure how to interpret it though...
If I start chia from cli it show logs normally.

Hope it helps. I can some other debug info if needed.

**Comment by maded2** [comment]
thanks, I think for some reason the log file can not be created.  PlotNG needs to able to continue to provide logging otherwise the chia plot create process will hangs.  I will push a fix soon and a release
